# This file is included early in main Makefile, don't set any targets
# to avoid overriding default (all) target

# Project definitions
REPO_NAME := Finnish Trams Fix
BASE_FILENAME := finnishtrams
REPO_VERSION := 2
NMLC_MONKEY := true
